name: "MobSF Scan"
description: "Sets up Python and performs MobSF security scan"
runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.8"

    - name: Run MobSF Security Scan
      uses: MobSF/mobsfscan@a60d10a83af68e23e0b30611c6515da604f06f65
      with:
        args: . --sarif --output results.sarif || true

    - name: Upload MobSF Report
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: results.sarif
