plugins {
    id 'com.android.library'
}
android {
    namespace 'dev.sogn.snaptune.shared'
    compileSdk 36

    defaultConfig {
        minSdk 28
        targetSdk 36

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
dependencies {
    implementation libs.androidx.media
}