build:
  # maxIssues: 0
  excludeCorrectable: false
  weights:
    # complexity: 2
    # LongParameterList: 1
    # style: 1
    # comments: 1

config:
  validation: true
  warningsAsErrors: false
  checkExhaustiveness: false
  # when writing own rules with new config properties, the edit distance between the property name and the
  # suggested property name must be less than or equal to this value.
  # default: 2

console-reports:
  active: true
  exclude:
    - "ProjectStatisticsReport"
    - "ComplexityReport"
    - "NotificationReport"
    - "FindingsReport"
    - "FileBasedFindingsReport"

naming:
  active: true
  FunctionNaming:
    active: true
    functionPattern: "[a-z][a-zA-Z0-9]*"
  ClassNaming:
    active: true
    classPattern: "[A-Z][a-zA-Z0-9]*"

complexity:
  active: true
  LongParameterList:
    active: true
    functionThreshold: 6
    constructorThreshold: 6
  TooManyFunctions:
    active: true
    thresholdInFiles: 20
    thresholdInClasses: 20
    thresholdInInterfaces: 20
    thresholdInObjects: 20
    thresholdInEnums: 20
